// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Not configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmLlRt_0eygATGRjiC1EXDmP9u5ry-DaY',
    appId: '1:1082631328396:android:afd4fb490e60ad42a7a1a9',
    messagingSenderId: '1082631328396',
    projectId: 'transport-assistant-2c59e',
    storageBucket: 'transport-assistant-2c59e.firebasestorage.app',
  );

  // ⚠️ iOS غير موجود في google-services.json
  // إذا ما تحتاج iOS اتركه هكذا
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmLlRt_0eygATGRjiC1EXDmP9u5ry-DaY',
    appId: '1:1082631328396:ios:afd4fb490e60ad42a7a1a9',
    messagingSenderId: '1082631328396',
    projectId: 'transport-assistant-2c59e',
    storageBucket: 'transport-assistant-2c59e.firebasestorage.app',
    iosBundleId: 'com.example.transportAssistant',
  );
}





// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAVMQJ5ms3uejgI-xlLV21g_hN_I2cyJFA',
//     appId: '1:637729050501:android:5838fa67b03ef5209fbeec',
//     messagingSenderId: '637729050501',
//     projectId: 'abdoufltter',
//     storageBucket: 'abdoufltter.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAQTmLUlilkM6iJ7Qpxyp12uK-Jy9URlFc',
//     appId: '1:637729050501:ios:d51edb2f288936e99fbeec',
//     messagingSenderId: '637729050501',
//     projectId: 'abdoufltter',
//     storageBucket: 'abdoufltter.firebasestorage.app',
//     iosClientId: '637729050501-p5tpcl59gau2cs6mllucnb28r3kjq88s.apps.googleusercontent.com',
//     iosBundleId: 'com.example.transportAssistant',
//   );
// }
